In [1]:
import numpy as np
import pandas as pd
import psycopg as pg
import mlflow
import os
from catboost import CatBoostClassifier
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import matplotlib.pyplot as plt

In [42]:
TABLE_NAME = "clean_users_churn"

TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000

EXPERIMENT_NAME = "Explore_search_hyperparams"
RUN_NAME = 'model_search'
REGISTRY_MODEL_NAME = "Applied_hyperparams"

In [3]:
configs = {"sslmode": "require", "target_session_attrs": "read-write"}
db_credits = {
    "host": os.getenv("DB_DESTINATION_HOST"),
    "port": os.getenv("DB_DESTINATION_PORT"),
    "dbname": os.getenv("DB_DESTINATION_NAME"),
    "user": os.getenv("DB_DESTINATION_USER"),
    "password": os.getenv("DB_DESTINATION_PASSWORD")
}

configs.update(db_credits)

In [4]:
with pg.connect(**configs) as conn:
    with conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {TABLE_NAME}")

        data = cur.fetchall()

        columns = [col.name for col in cur.description]

In [5]:
df = pd.DataFrame(data=data, columns=columns)

In [6]:
features = ["monthly_charges", "total_charges", "senior_citizen"]
target = "target"

In [7]:
df[features]

      monthly_charges  total_charges  senior_citizen
0               19.80         202.25               0
1               20.15          20.15               0
2               59.90        3505.10               0
3               59.60        2970.30               0
4               55.30        1530.60               0
...               ...            ...             ...
7019            69.50        1652.10               0
7020            76.00        1588.75               0
7021            93.60        3366.05               0
7022            95.65         778.10               0
7023           100.55        7113.75               0

[7024 rows x 3 columns]

In [7]:
test_size = 0.2
split_column = features

In [8]:
df.sort_values(by=["begin_date"], inplace=True)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], test_size=test_size, shuffle=False)

In [10]:
X_train

      monthly_charges  total_charges  senior_citizen
4367            92.45        6440.25               1
4462           117.80        8684.80               0
3317           104.15        7689.95               1
951            108.05        7532.15               0
6850           108.60        7690.90               0
...               ...            ...             ...
4006            89.00         605.45               1
2964            77.85         299.20               0
5719            34.20         256.60               0
3216            75.35         564.65               0
2873            70.25         331.90               1

[5619 rows x 3 columns]

In [11]:
print(f"Размер выборки для обучения: {X_train.shape}")
print(f"Размер выборки для теста: {X_test.shape}")

Размер выборки для обучения: (5619, 3)
Размер выборки для теста: (1405, 3)

In [12]:
loss_function = "Logloss"
task_type = 'CPU'
random_seed = 0
iterations = 300
verbose = False

In [ ]:
param_grid = {
    'iterations': [50, 100, 300, 500],
    'learning_rate': [0.01, 0.1, 0.3],
    'loss_function': ["Logloss", "MultiClass"],
    'depth': [4, 6, 8, 10],
    'min_data_in_leaf': [50, 100, 200],
}

In [19]:
params_distribution = {
    'iterations': [50, 100, 300, 500],
    'learning_rate': [0.01, 0.1, 0.3],
    'loss_function': ["Logloss", "MultiClass"],
    'depth': np.arange(1, 10),
    'min_data_in_leaf': np.arange(10, 200, 10),
}

In [20]:
model = CatBoostClassifier(random_seed=random_seed, task_type=task_type)

In [21]:
cv = RandomizedSearchCV(estimator=model, param_distributions=params_distribution, cv=2, scoring='roc_auc', n_jobs=-1)

In [24]:
cv = GridSearchCV(estimator=model, param_grid=param_grid, cv=2, scoring="roc_auc", n_jobs=-1)

In [22]:
clf = cv.fit(X_train, y_train)

0:	learn: 0.6426823	total: 72ms	remaining: 3.53s
0:	learn: 0.6600946	total: 72.1ms	remaining: 3.53s
1:	learn: 0.5980039	total: 81.9ms	remaining: 1.97s
1:	learn: 0.6105498	total: 80.9ms	remaining: 1.94s
2:	learn: 0.5596083	total: 90ms	remaining: 1.41s
3:	learn: 0.5295307	total: 91.8ms	remaining: 1.05s
2:	learn: 0.5695092	total: 85ms	remaining: 1.33s
4:	learn: 0.5059957	total: 93.3ms	remaining: 840ms
3:	learn: 0.5370124	total: 90.6ms	remaining: 1.04s
4:	learn: 0.5125520	total: 92.7ms	remaining: 834ms
5:	learn: 0.4821196	total: 106ms	remaining: 780ms
6:	learn: 0.4617777	total: 111ms	remaining: 681ms
5:	learn: 0.4875642	total: 101ms	remaining: 744ms
7:	learn: 0.4436756	total: 119ms	remaining: 622ms
6:	learn: 0.4657542	total: 106ms	remaining: 652ms
8:	learn: 0.4255513	total: 127ms	remaining: 576ms
9:	learn: 0.4125158	total: 128ms	remaining: 513ms
7:	learn: 0.4453083	total: 110ms	remaining: 580ms
10:	learn: 0.3997061	total: 134ms	remaining: 477ms
11:	learn: 0.3910318	total: 136ms	remaining: 430ms
8:	learn: 0.4280506	total: 115ms	remaining: 523ms
12:	learn: 0.3806949	total: 144ms	remaining: 410ms
9:	learn: 0.4127531	total: 119ms	remaining: 476ms
13:	learn: 0.3715215	total: 150ms	remaining: 384ms
10:	learn: 0.3998933	total: 121ms	remaining: 429ms
14:	learn: 0.3623198	total: 158ms	remaining: 369ms
11:	learn: 0.3882568	total: 127ms	remaining: 403ms
15:	learn: 0.3553050	total: 166ms	remaining: 352ms
12:	learn: 0.3779174	total: 131ms	remaining: 373ms
16:	learn: 0.3484516	total: 173ms	remaining: 337ms
17:	learn: 0.3430636	total: 177ms	remaining: 315ms
13:	learn: 0.3690725	total: 135ms	remaining: 347ms
14:	learn: 0.3627108	total: 138ms	remaining: 322ms
18:	learn: 0.3375062	total: 187ms	remaining: 305ms
15:	learn: 0.3547395	total: 144ms	remaining: 305ms
19:	learn: 0.3321713	total: 196ms	remaining: 294ms
16:	learn: 0.3481007	total: 151ms	remaining: 293ms
20:	learn: 0.3282357	total: 204ms	remaining: 282ms
17:	learn: 0.3413759	total: 156ms	remaining: 278ms
21:	learn: 0.3235649	total: 211ms	remaining: 269ms
18:	learn: 0.3363425	total: 160ms	remaining: 261ms
22:	learn: 0.3191652	total: 217ms	remaining: 255ms
19:	learn: 0.3327796	total: 162ms	remaining: 243ms
23:	learn: 0.3157641	total: 225ms	remaining: 244ms
20:	learn: 0.3277773	total: 168ms	remaining: 232ms
24:	learn: 0.3128100	total: 231ms	remaining: 231ms
21:	learn: 0.3238653	total: 172ms	remaining: 219ms
25:	learn: 0.3094173	total: 239ms	remaining: 220ms
22:	learn: 0.3193544	total: 180ms	remaining: 211ms
26:	learn: 0.3077606	total: 243ms	remaining: 207ms
23:	learn: 0.3150385	total: 191ms	remaining: 206ms
27:	learn: 0.3058631	total: 253ms	remaining: 199ms
24:	learn: 0.3122208	total: 201ms	remaining: 201ms
28:	learn: 0.3040656	total: 262ms	remaining: 190ms
25:	learn: 0.3089488	total: 214ms	remaining: 198ms
29:	learn: 0.3019790	total: 273ms	remaining: 182ms
30:	learn: 0.3001432	total: 282ms	remaining: 173ms
26:	learn: 0.3055246	total: 227ms	remaining: 193ms
27:	learn: 0.3039683	total: 233ms	remaining: 183ms
31:	learn: 0.2985455	total: 291ms	remaining: 163ms
28:	learn: 0.3010331	total: 241ms	remaining: 174ms
32:	learn: 0.2965869	total: 302ms	remaining: 156ms
33:	learn: 0.2963823	total: 304ms	remaining: 143ms
29:	learn: 0.2985211	total: 252ms	remaining: 168ms
30:	learn: 0.2975045	total: 256ms	remaining: 157ms
34:	learn: 0.2949002	total: 314ms	remaining: 135ms
35:	learn: 0.2943146	total: 317ms	remaining: 123ms
36:	learn: 0.2942240	total: 320ms	remaining: 112ms
31:	learn: 0.2960365	total: 265ms	remaining: 149ms
37:	learn: 0.2928288	total: 329ms	remaining: 104ms
32:	learn: 0.2944114	total: 278ms	remaining: 143ms
38:	learn: 0.2914336	total: 337ms	remaining: 95.1ms
33:	learn: 0.2941675	total: 283ms	remaining: 133ms
34:	learn: 0.2932923	total: 288ms	remaining: 124ms
39:	learn: 0.2903150	total: 347ms	remaining: 86.9ms
35:	learn: 0.2918688	total: 293ms	remaining: 114ms
40:	learn: 0.2901583	total: 350ms	remaining: 76.7ms
36:	learn: 0.2913277	total: 296ms	remaining: 104ms
37:	learn: 0.2907190	total: 300ms	remaining: 94.6ms
41:	learn: 0.2887672	total: 358ms	remaining: 68.2ms
38:	learn: 0.2883791	total: 309ms	remaining: 87.1ms
42:	learn: 0.2879096	total: 369ms	remaining: 60ms
39:	learn: 0.2869202	total: 318ms	remaining: 79.4ms
43:	learn: 0.2871263	total: 372ms	remaining: 50.7ms
44:	learn: 0.2859906	total: 378ms	remaining: 42ms
40:	learn: 0.2852468	total: 331ms	remaining: 72.7ms
45:	learn: 0.2850833	total: 389ms	remaining: 33.8ms
41:	learn: 0.2836785	total: 343ms	remaining: 65.3ms
46:	learn: 0.2839375	total: 401ms	remaining: 25.6ms
42:	learn: 0.2825852	total: 351ms	remaining: 57.2ms
43:	learn: 0.2814973	total: 361ms	remaining: 49.2ms
47:	learn: 0.2833483	total: 413ms	remaining: 17.2ms
48:	learn: 0.2825844	total: 422ms	remaining: 8.6ms
44:	learn: 0.2805618	total: 380ms	remaining: 42.2ms
49:	learn: 0.2819417	total: 432ms	remaining: 0us
45:	learn: 0.2798044	total: 386ms	remaining: 33.6ms
46:	learn: 0.2785208	total: 390ms	remaining: 24.9ms
47:	learn: 0.2779573	total: 394ms	remaining: 16.4ms
48:	learn: 0.2772327	total: 397ms	remaining: 8.11ms
49:	learn: 0.2768590	total: 399ms	remaining: 0us
0:	learn: 0.6426823	total: 1.56ms	remaining: 76.4ms
1:	learn: 0.5983025	total: 3.78ms	remaining: 90.7ms
2:	learn: 0.5617494	total: 5.72ms	remaining: 89.6ms
3:	learn: 0.5316874	total: 7.68ms	remaining: 88.3ms
0:	learn: 0.6600946	total: 1.27ms	remaining: 62.2ms
1:	learn: 0.6130200	total: 3.18ms	remaining: 76.4ms
4:	learn: 0.5055873	total: 13.8ms	remaining: 124ms
2:	learn: 0.5720951	total: 6.52ms	remaining: 102ms
5:	learn: 0.4816145	total: 17.4ms	remaining: 128ms
6:	learn: 0.4606263	total: 21.2ms	remaining: 130ms
3:	learn: 0.5376683	total: 9.57ms	remaining: 110ms
7:	learn: 0.4429445	total: 24.8ms	remaining: 130ms
4:	learn: 0.5089137	total: 11.4ms	remaining: 103ms
8:	learn: 0.4286550	total: 28.2ms	remaining: 129ms
9:	learn: 0.4155861	total: 30ms	remaining: 120ms
5:	learn: 0.4883240	total: 12.7ms	remaining: 93ms
10:	learn: 0.4035029	total: 33.7ms	remaining: 120ms
6:	learn: 0.4668767	total: 14.5ms	remaining: 88.8ms
11:	learn: 0.3948045	total: 35ms	remaining: 111ms
12:	learn: 0.3845140	total: 38.1ms	remaining: 108ms
7:	learn: 0.4520257	total: 16.7ms	remaining: 87.7ms
13:	learn: 0.3747592	total: 41.9ms	remaining: 108ms
8:	learn: 0.4350932	total: 18.6ms	remaining: 84.6ms
14:	learn: 0.3662589	total: 46ms	remaining: 107ms
9:	learn: 0.4198425	total: 20.7ms	remaining: 82.9ms
15:	learn: 0.3595331	total: 49.5ms	remaining: 105ms
16:	learn: 0.3545197	total: 51.4ms	remaining: 99.7ms
10:	learn: 0.4092805	total: 22.4ms	remaining: 79.5ms
17:	learn: 0.3495391	total: 55ms	remaining: 97.8ms
11:	learn: 0.3960217	total: 25.1ms	remaining: 79.3ms
18:	learn: 0.3440807	total: 58.3ms	remaining: 95.1ms
12:	learn: 0.3874427	total: 26.1ms	remaining: 74.2ms
19:	learn: 0.3386331	total: 62.1ms	remaining: 93.1ms
13:	learn: 0.3782768	total: 28.5ms	remaining: 73.2ms
14:	learn: 0.3704499	total: 32.1ms	remaining: 74.9ms
15:	learn: 0.3625419	total: 34.1ms	remaining: 72.4ms
16:	learn: 0.3562570	total: 35.8ms	remaining: 69.5ms
17:	learn: 0.3488988	total: 38.1ms	remaining: 67.8ms
20:	learn: 0.3342904	total: 72.4ms	remaining: 99.9ms
18:	learn: 0.3426756	total: 41.4ms	remaining: 67.6ms
19:	learn: 0.3377228	total: 43.4ms	remaining: 65ms
21:	learn: 0.3316100	total: 73.8ms	remaining: 93.9ms
20:	learn: 0.3324403	total: 47ms	remaining: 64.9ms
22:	learn: 0.3275082	total: 75.5ms	remaining: 88.6ms
21:	learn: 0.3299509	total: 48.8ms	remaining: 62.1ms
22:	learn: 0.3263898	total: 52.5ms	remaining: 61.6ms
23:	learn: 0.3244172	total: 79.5ms	remaining: 86.2ms
23:	learn: 0.3230619	total: 56.3ms	remaining: 61ms
24:	learn: 0.3192182	total: 58.1ms	remaining: 58.1ms
24:	learn: 0.3221689	total: 81.4ms	remaining: 81.4ms
25:	learn: 0.3169735	total: 61.6ms	remaining: 56.9ms
25:	learn: 0.3186956	total: 83.1ms	remaining: 76.7ms
26:	learn: 0.3150226	total: 63.4ms	remaining: 54ms
26:	learn: 0.3156596	total: 86.6ms	remaining: 73.8ms
27:	learn: 0.3123590	total: 65.1ms	remaining: 51.2ms
28:	learn: 0.3096357	total: 68ms	remaining: 49.2ms
27:	learn: 0.3130625	total: 94.1ms	remaining: 74ms
29:	learn: 0.3076536	total: 73ms	remaining: 48.7ms
28:	learn: 0.3101983	total: 96.5ms	remaining: 69.9ms
29:	learn: 0.3081011	total: 98.7ms	remaining: 65.8ms
30:	learn: 0.3051357	total: 78.2ms	remaining: 47.9ms
30:	learn: 0.3069110	total: 105ms	remaining: 64.2ms
31:	learn: 0.3051555	total: 107ms	remaining: 60.2ms
31:	learn: 0.3033308	total: 84.4ms	remaining: 47.5ms
32:	learn: 0.3038834	total: 110ms	remaining: 56.4ms
32:	learn: 0.3014475	total: 88.2ms	remaining: 45.4ms
33:	learn: 0.3020436	total: 113ms	remaining: 53.4ms
33:	learn: 0.2994713	total: 92.5ms	remaining: 43.5ms
34:	learn: 0.3002481	total: 119ms	remaining: 51ms
35:	learn: 0.2992591	total: 121ms	remaining: 47.2ms
34:	learn: 0.2980807	total: 98.6ms	remaining: 42.2ms
35:	learn: 0.2967545	total: 102ms	remaining: 39.5ms
36:	learn: 0.2972938	total: 128ms	remaining: 45ms
37:	learn: 0.2967312	total: 130ms	remaining: 41ms
38:	learn: 0.2959222	total: 133ms	remaining: 37.6ms
36:	learn: 0.2953630	total: 108ms	remaining: 37.9ms
39:	learn: 0.2945098	total: 139ms	remaining: 34.7ms
37:	learn: 0.2943652	total: 112ms	remaining: 35.4ms
40:	learn: 0.2933364	total: 141ms	remaining: 31ms
38:	learn: 0.2935382	total: 116ms	remaining: 32.9ms
41:	learn: 0.2926164	total: 148ms	remaining: 28.2ms
42:	learn: 0.2919310	total: 151ms	remaining: 24.5ms
39:	learn: 0.2926280	total: 122ms	remaining: 30.5ms
40:	learn: 0.2921003	total: 126ms	remaining: 27.6ms
43:	learn: 0.2909158	total: 158ms	remaining: 21.5ms
44:	learn: 0.2908794	total: 159ms	remaining: 17.6ms
41:	learn: 0.2914558	total: 131ms	remaining: 25ms
45:	learn: 0.2900169	total: 162ms	remaining: 14.1ms
42:	learn: 0.2906691	total: 135ms	remaining: 22.1ms
46:	learn: 0.2890434	total: 168ms	remaining: 10.7ms
47:	learn: 0.2885188	total: 170ms	remaining: 7.09ms
43:	learn: 0.2900475	total: 141ms	remaining: 19.2ms
48:	learn: 0.2875494	total: 177ms	remaining: 3.61ms
44:	learn: 0.2896822	total: 145ms	remaining: 16.1ms
49:	learn: 0.2865142	total: 180ms	remaining: 0us
45:	learn: 0.2884268	total: 149ms	remaining: 12.9ms
46:	learn: 0.2860960	total: 151ms	remaining: 9.63ms
47:	learn: 0.2853323	total: 153ms	remaining: 6.37ms
48:	learn: 0.2848621	total: 155ms	remaining: 3.16ms
49:	learn: 0.2848373	total: 156ms	remaining: 0us
0:	learn: 0.6880489	total: 2.58ms	remaining: 771ms
1:	learn: 0.6828804	total: 3.73ms	remaining: 555ms
2:	learn: 0.6778087	total: 4.85ms	remaining: 480ms
3:	learn: 0.6729933	total: 6.06ms	remaining: 449ms
4:	learn: 0.6682033	total: 7.25ms	remaining: 428ms
5:	learn: 0.6635114	total: 8.54ms	remaining: 419ms
6:	learn: 0.6587771	total: 9.83ms	remaining: 411ms
7:	learn: 0.6542767	total: 11.6ms	remaining: 423ms
8:	learn: 0.6500582	total: 12.7ms	remaining: 411ms
9:	learn: 0.6457139	total: 13.8ms	remaining: 400ms
10:	learn: 0.6420959	total: 14.9ms	remaining: 390ms
11:	learn: 0.6378783	total: 15.9ms	remaining: 382ms
12:	learn: 0.6338849	total: 17ms	remaining: 376ms
13:	learn: 0.6302823	total: 18.1ms	remaining: 370ms
0:	learn: 0.6896860	total: 10.8ms	remaining: 3.22s
14:	learn: 0.6263226	total: 19.5ms	remaining: 370ms
1:	learn: 0.6848167	total: 12.2ms	remaining: 1.81s
15:	learn: 0.6223706	total: 20.8ms	remaining: 370ms
2:	learn: 0.6799667	total: 13.5ms	remaining: 1.33s
16:	learn: 0.6185423	total: 23.5ms	remaining: 390ms
17:	learn: 0.6146714	total: 24.7ms	remaining: 387ms
18:	learn: 0.6111148	total: 25.8ms	remaining: 381ms
19:	learn: 0.6074546	total: 26.9ms	remaining: 377ms
20:	learn: 0.6037954	total: 28.1ms	remaining: 374ms
21:	learn: 0.6001531	total: 29.3ms	remaining: 370ms
22:	learn: 0.5968176	total: 30.3ms	remaining: 365ms
23:	learn: 0.5933135	total: 31.2ms	remaining: 359ms
24:	learn: 0.5897199	total: 32.2ms	remaining: 354ms
25:	learn: 0.5862774	total: 33.1ms	remaining: 349ms
3:	learn: 0.6752305	total: 26.8ms	remaining: 1.98s
26:	learn: 0.5830860	total: 34.5ms	remaining: 349ms
4:	learn: 0.6702047	total: 28.1ms	remaining: 1.66s
27:	learn: 0.5798269	total: 35.9ms	remaining: 348ms
5:	learn: 0.6657483	total: 29.3ms	remaining: 1.44s
28:	learn: 0.5766937	total: 37.1ms	remaining: 346ms
29:	learn: 0.5736526	total: 38.4ms	remaining: 345ms
30:	learn: 0.5705894	total: 39.7ms	remaining: 344ms
31:	learn: 0.5678911	total: 40.9ms	remaining: 343ms
32:	learn: 0.5648926	total: 42ms	remaining: 340ms
33:	learn: 0.5619560	total: 42.9ms	remaining: 336ms
34:	learn: 0.5591149	total: 44ms	remaining: 334ms
35:	learn: 0.5561716	total: 45.1ms	remaining: 331ms
36:	learn: 0.5532096	total: 46.1ms	remaining: 328ms
37:	learn: 0.5502325	total: 47.1ms	remaining: 325ms
38:	learn: 0.5473422	total: 48.1ms	remaining: 322ms
6:	learn: 0.6614682	total: 37.1ms	remaining: 1.55s
39:	learn: 0.5446534	total: 49.4ms	remaining: 321ms
7:	learn: 0.6568930	total: 38.5ms	remaining: 1.4s
40:	learn: 0.5420022	total: 50.8ms	remaining: 321ms
41:	learn: 0.5395721	total: 52.1ms	remaining: 320ms
42:	learn: 0.5370398	total: 53.4ms	remaining: 319ms
43:	learn: 0.5345470	total: 54.6ms	remaining: 318ms
44:	learn: 0.5320371	total: 55.8ms	remaining: 316ms
8:	learn: 0.6523329	total: 45.6ms	remaining: 1.47s
9:	learn: 0.6479584	total: 46.5ms	remaining: 1.35s
45:	learn: 0.5294453	total: 58.5ms	remaining: 323ms
10:	learn: 0.6434716	total: 47.5ms	remaining: 1.25s
11:	learn: 0.6391760	total: 48.5ms	remaining: 1.16s
46:	learn: 0.5276532	total: 61.7ms	remaining: 332ms
47:	learn: 0.5252447	total: 63ms	remaining: 331ms
48:	learn: 0.5229487	total: 64.4ms	remaining: 330ms
12:	learn: 0.6349442	total: 49.4ms	remaining: 1.09s
49:	learn: 0.5205351	total: 65.5ms	remaining: 328ms
13:	learn: 0.6313389	total: 50.3ms	remaining: 1.03s
14:	learn: 0.6273003	total: 51.2ms	remaining: 972ms
15:	learn: 0.6236910	total: 53ms	remaining: 941ms
50:	learn: 0.5181823	total: 70.3ms	remaining: 343ms
16:	learn: 0.6199062	total: 54.8ms	remaining: 912ms
51:	learn: 0.5158735	total: 71.7ms	remaining: 342ms
17:	learn: 0.6160126	total: 55.7ms	remaining: 873ms
52:	learn: 0.5138915	total: 73.7ms	remaining: 344ms
53:	learn: 0.5120638	total: 74.7ms	remaining: 340ms
54:	learn: 0.5098787	total: 76ms	remaining: 339ms
55:	learn: 0.5077115	total: 77.4ms	remaining: 337ms
56:	learn: 0.5056095	total: 78.7ms	remaining: 336ms
18:	learn: 0.6125268	total: 62.2ms	remaining: 920ms
19:	learn: 0.6088791	total: 63.2ms	remaining: 885ms
57:	learn: 0.5034437	total: 79.6ms	remaining: 332ms
20:	learn: 0.6051636	total: 65.2ms	remaining: 866ms
21:	learn: 0.6017866	total: 66.1ms	remaining: 836ms
58:	learn: 0.5014638	total: 82ms	remaining: 335ms
22:	learn: 0.5982615	total: 68.3ms	remaining: 822ms
23:	learn: 0.5948053	total: 69.7ms	remaining: 802ms
59:	learn: 0.4994662	total: 86.9ms	remaining: 347ms
60:	learn: 0.4976648	total: 87.9ms	remaining: 344ms
24:	learn: 0.5913878	total: 72.9ms	remaining: 802ms
61:	learn: 0.4958246	total: 89.3ms	remaining: 343ms
62:	learn: 0.4939466	total: 90.5ms	remaining: 341ms
25:	learn: 0.5884452	total: 75.9ms	remaining: 800ms
63:	learn: 0.4918599	total: 91.4ms	remaining: 337ms
26:	learn: 0.5848883	total: 77.2ms	remaining: 781ms
64:	learn: 0.4899260	total: 92.4ms	remaining: 334ms
65:	learn: 0.4879331	total: 93.3ms	remaining: 331ms
27:	learn: 0.5822096	total: 80.2ms	remaining: 779ms
28:	learn: 0.5789895	total: 81.5ms	remaining: 762ms
66:	learn: 0.4860384	total: 94.4ms	remaining: 328ms
67:	learn: 0.4841022	total: 95.3ms	remaining: 325ms
29:	learn: 0.5758771	total: 84.4ms	remaining: 760ms
30:	learn: 0.5725349	total: 86ms	remaining: 746ms
68:	learn: 0.4822977	total: 96.9ms	remaining: 324ms
31:	learn: 0.5702579	total: 87.3ms	remaining: 731ms
32:	learn: 0.5672154	total: 88.6ms	remaining: 717ms
69:	learn: 0.4804193	total: 98.8ms	remaining: 325ms
70:	learn: 0.4789773	total: 100ms	remaining: 323ms
71:	learn: 0.4772034	total: 101ms	remaining: 320ms
33:	learn: 0.5640770	total: 92.4ms	remaining: 723ms
34:	learn: 0.5610753	total: 93.7ms	remaining: 710ms
35:	learn: 0.5590290	total: 94.8ms	remaining: 695ms
72:	learn: 0.4754599	total: 104ms	remaining: 323ms
36:	learn: 0.5564160	total: 96.5ms	remaining: 686ms
37:	learn: 0.5535668	total: 97.5ms	remaining: 672ms
38:	learn: 0.5507441	total: 98.7ms	remaining: 661ms
73:	learn: 0.4737930	total: 108ms	remaining: 331ms
74:	learn: 0.4721044	total: 109ms	remaining: 327ms
75:	learn: 0.4703596	total: 110ms	remaining: 324ms
76:	learn: 0.4687778	total: 111ms	remaining: 322ms
77:	learn: 0.4671834	total: 112ms	remaining: 319ms
39:	learn: 0.5479623	total: 105ms	remaining: 679ms
40:	learn: 0.5454225	total: 106ms	remaining: 670ms
78:	learn: 0.4655059	total: 114ms	remaining: 318ms
79:	learn: 0.4638595	total: 115ms	remaining: 316ms
41:	learn: 0.5426053	total: 107ms	remaining: 658ms
42:	learn: 0.5400639	total: 108ms	remaining: 648ms
80:	learn: 0.4622690	total: 117ms	remaining: 316ms
81:	learn: 0.4606932	total: 118ms	remaining: 314ms
43:	learn: 0.5376324	total: 111ms	remaining: 647ms
44:	learn: 0.5351258	total: 113ms	remaining: 638ms
82:	learn: 0.4590650	total: 119ms	remaining: 311ms
45:	learn: 0.5325170	total: 114ms	remaining: 627ms
83:	learn: 0.4574598	total: 120ms	remaining: 308ms
46:	learn: 0.5307224	total: 117ms	remaining: 631ms
84:	learn: 0.4559993	total: 122ms	remaining: 308ms
47:	learn: 0.5283052	total: 119ms	remaining: 625ms
48:	learn: 0.5259516	total: 120ms	remaining: 615ms
85:	learn: 0.4545218	total: 125ms	remaining: 311ms
49:	learn: 0.5238363	total: 122ms	remaining: 610ms
50:	learn: 0.5215500	total: 123ms	remaining: 601ms
51:	learn: 0.5192704	total: 124ms	remaining: 593ms
52:	learn: 0.5171497	total: 125ms	remaining: 584ms
86:	learn: 0.4530449	total: 130ms	remaining: 319ms
87:	learn: 0.4515759	total: 132ms	remaining: 317ms
88:	learn: 0.4500327	total: 134ms	remaining: 317ms
89:	learn: 0.4486541	total: 135ms	remaining: 314ms
90:	learn: 0.4474862	total: 136ms	remaining: 312ms
91:	learn: 0.4460678	total: 137ms	remaining: 309ms
53:	learn: 0.5155768	total: 130ms	remaining: 594ms
54:	learn: 0.5138001	total: 131ms	remaining: 584ms
55:	learn: 0.5114209	total: 132ms	remaining: 577ms
56:	learn: 0.5092675	total: 134ms	remaining: 569ms
92:	learn: 0.4446723	total: 140ms	remaining: 311ms
93:	learn: 0.4433394	total: 141ms	remaining: 309ms
94:	learn: 0.4418967	total: 142ms	remaining: 307ms
57:	learn: 0.5071333	total: 138ms	remaining: 575ms
95:	learn: 0.4406049	total: 143ms	remaining: 304ms
58:	learn: 0.5049469	total: 139ms	remaining: 567ms
59:	learn: 0.5030096	total: 140ms	remaining: 560ms
96:	learn: 0.4393697	total: 145ms	remaining: 302ms
60:	learn: 0.5009479	total: 143ms	remaining: 560ms
61:	learn: 0.4988086	total: 144ms	remaining: 552ms
62:	learn: 0.4967114	total: 145ms	remaining: 546ms
63:	learn: 0.4946225	total: 146ms	remaining: 538ms
97:	learn: 0.4380844	total: 150ms	remaining: 309ms
64:	learn: 0.4926372	total: 147ms	remaining: 531ms
65:	learn: 0.4906084	total: 148ms	remaining: 524ms
98:	learn: 0.4367773	total: 152ms	remaining: 308ms
66:	learn: 0.4889167	total: 149ms	remaining: 519ms
99:	learn: 0.4355877	total: 154ms	remaining: 308ms
100:	learn: 0.4342716	total: 155ms	remaining: 305ms
67:	learn: 0.4872152	total: 150ms	remaining: 512ms
101:	learn: 0.4330767	total: 157ms	remaining: 304ms
102:	learn: 0.4319248	total: 158ms	remaining: 302ms
103:	learn: 0.4308128	total: 159ms	remaining: 299ms
68:	learn: 0.4853759	total: 151ms	remaining: 507ms
104:	learn: 0.4296821	total: 161ms	remaining: 299ms
105:	learn: 0.4285194	total: 162ms	remaining: 297ms
106:	learn: 0.4274966	total: 163ms	remaining: 294ms
107:	learn: 0.4264902	total: 164ms	remaining: 292ms
69:	learn: 0.4841491	total: 156ms	remaining: 514ms
70:	learn: 0.4822800	total: 157ms	remaining: 507ms
71:	learn: 0.4806980	total: 159ms	remaining: 503ms
72:	learn: 0.4790793	total: 160ms	remaining: 498ms
108:	learn: 0.4254361	total: 167ms	remaining: 293ms
109:	learn: 0.4243999	total: 169ms	remaining: 291ms
73:	learn: 0.4775994	total: 163ms	remaining: 498ms
74:	learn: 0.4758212	total: 164ms	remaining: 492ms
75:	learn: 0.4740305	total: 165ms	remaining: 487ms
110:	learn: 0.4233359	total: 173ms	remaining: 295ms
76:	learn: 0.4723870	total: 167ms	remaining: 485ms

In [23]:
print("Лучшие гиперпараметры:", clf.best_params_)
print("Лучший счет:", clf.best_score_)

Лучшие гиперпараметры: {'min_data_in_leaf': 10, 'loss_function': 'MultiClass', 'learning_rate': 0.1, 'iterations': 100, 'depth': 3}
Лучший счет: 0.8032461936938639

In [24]:
best_model = clf.best_estimator_

In [25]:
best_model.fit(X_train, y_train)

0:	learn: 0.6603001	total: 1.73ms	remaining: 171ms
1:	learn: 0.6252010	total: 3.7ms	remaining: 181ms
2:	learn: 0.5961991	total: 5.41ms	remaining: 175ms
3:	learn: 0.5725272	total: 7.14ms	remaining: 171ms
4:	learn: 0.5518655	total: 9.15ms	remaining: 174ms
5:	learn: 0.5341208	total: 10.8ms	remaining: 169ms
6:	learn: 0.5196833	total: 12.5ms	remaining: 166ms
7:	learn: 0.5064808	total: 14.2ms	remaining: 164ms
8:	learn: 0.4953497	total: 15.8ms	remaining: 160ms
9:	learn: 0.4861007	total: 17.4ms	remaining: 157ms
10:	learn: 0.4779315	total: 19.1ms	remaining: 154ms
11:	learn: 0.4710818	total: 20.8ms	remaining: 153ms
12:	learn: 0.4645891	total: 22.6ms	remaining: 151ms
13:	learn: 0.4592762	total: 24.4ms	remaining: 150ms
14:	learn: 0.4541532	total: 26.1ms	remaining: 148ms
15:	learn: 0.4491152	total: 27.8ms	remaining: 146ms
16:	learn: 0.4453381	total: 29.5ms	remaining: 144ms
17:	learn: 0.4413528	total: 31.2ms	remaining: 142ms
18:	learn: 0.4394500	total: 32.9ms	remaining: 140ms
19:	learn: 0.4353733	total: 34.6ms	remaining: 138ms
20:	learn: 0.4327652	total: 36.3ms	remaining: 136ms
21:	learn: 0.4305654	total: 37.9ms	remaining: 134ms
22:	learn: 0.4275683	total: 39.6ms	remaining: 133ms
23:	learn: 0.4249817	total: 41.3ms	remaining: 131ms
24:	learn: 0.4226555	total: 43ms	remaining: 129ms
25:	learn: 0.4207502	total: 44.8ms	remaining: 127ms
26:	learn: 0.4189674	total: 46.5ms	remaining: 126ms
27:	learn: 0.4176952	total: 48.4ms	remaining: 124ms
28:	learn: 0.4159312	total: 50ms	remaining: 123ms
29:	learn: 0.4146738	total: 51.8ms	remaining: 121ms
30:	learn: 0.4135576	total: 53.5ms	remaining: 119ms
31:	learn: 0.4125161	total: 56.5ms	remaining: 120ms
32:	learn: 0.4118067	total: 58.1ms	remaining: 118ms
33:	learn: 0.4105188	total: 59.8ms	remaining: 116ms
34:	learn: 0.4088102	total: 61.5ms	remaining: 114ms
35:	learn: 0.4075514	total: 63.1ms	remaining: 112ms
36:	learn: 0.4068263	total: 64.9ms	remaining: 110ms
37:	learn: 0.4061897	total: 66.5ms	remaining: 109ms
38:	learn: 0.4051860	total: 68.2ms	remaining: 107ms
39:	learn: 0.4043358	total: 69.9ms	remaining: 105ms
40:	learn: 0.4039070	total: 71.6ms	remaining: 103ms
41:	learn: 0.4032605	total: 73.3ms	remaining: 101ms
42:	learn: 0.4024898	total: 75ms	remaining: 99.5ms
43:	learn: 0.4017352	total: 76.7ms	remaining: 97.6ms
44:	learn: 0.4012134	total: 78.3ms	remaining: 95.7ms
45:	learn: 0.4007206	total: 79.9ms	remaining: 93.8ms
46:	learn: 0.4005792	total: 81.5ms	remaining: 91.9ms
47:	learn: 0.4001120	total: 83.2ms	remaining: 90.1ms
48:	learn: 0.3992440	total: 84.9ms	remaining: 88.4ms
49:	learn: 0.3987549	total: 86.5ms	remaining: 86.5ms
50:	learn: 0.3985451	total: 88.1ms	remaining: 84.7ms
51:	learn: 0.3980059	total: 89.8ms	remaining: 82.9ms
52:	learn: 0.3977534	total: 91.4ms	remaining: 81.1ms
53:	learn: 0.3972722	total: 93.4ms	remaining: 79.5ms
54:	learn: 0.3967880	total: 95.2ms	remaining: 77.9ms
55:	learn: 0.3963707	total: 96.8ms	remaining: 76.1ms
56:	learn: 0.3958990	total: 98.4ms	remaining: 74.2ms
57:	learn: 0.3956128	total: 100ms	remaining: 72.5ms
58:	learn: 0.3953867	total: 102ms	remaining: 70.7ms
59:	learn: 0.3951976	total: 103ms	remaining: 68.9ms
60:	learn: 0.3949626	total: 105ms	remaining: 67.2ms
61:	learn: 0.3948663	total: 107ms	remaining: 65.4ms
62:	learn: 0.3948044	total: 108ms	remaining: 63.7ms
63:	learn: 0.3946236	total: 110ms	remaining: 61.9ms
64:	learn: 0.3943459	total: 112ms	remaining: 60.2ms
65:	learn: 0.3941628	total: 113ms	remaining: 58.5ms
66:	learn: 0.3938525	total: 115ms	remaining: 56.7ms
67:	learn: 0.3935793	total: 117ms	remaining: 55ms
68:	learn: 0.3932456	total: 119ms	remaining: 53.3ms
69:	learn: 0.3930604	total: 120ms	remaining: 51.5ms
70:	learn: 0.3929128	total: 122ms	remaining: 49.8ms
71:	learn: 0.3926546	total: 124ms	remaining: 48.1ms
72:	learn: 0.3924350	total: 125ms	remaining: 46.3ms
73:	learn: 0.3921272	total: 127ms	remaining: 44.6ms
74:	learn: 0.3918124	total: 129ms	remaining: 42.9ms
75:	learn: 0.3917453	total: 130ms	remaining: 41.1ms
76:	learn: 0.3916294	total: 132ms	remaining: 39.4ms
77:	learn: 0.3915135	total: 133ms	remaining: 37.6ms
78:	learn: 0.3912381	total: 135ms	remaining: 35.9ms
79:	learn: 0.3910479	total: 137ms	remaining: 34.2ms
80:	learn: 0.3907500	total: 139ms	remaining: 32.5ms
81:	learn: 0.3906687	total: 140ms	remaining: 30.8ms
82:	learn: 0.3905715	total: 142ms	remaining: 29.1ms
83:	learn: 0.3904312	total: 144ms	remaining: 27.4ms
84:	learn: 0.3901491	total: 145ms	remaining: 25.6ms
85:	learn: 0.3900832	total: 147ms	remaining: 23.9ms
86:	learn: 0.3900092	total: 149ms	remaining: 22.2ms
87:	learn: 0.3898628	total: 150ms	remaining: 20.5ms
88:	learn: 0.3897412	total: 152ms	remaining: 18.8ms
89:	learn: 0.3895267	total: 154ms	remaining: 17.1ms
90:	learn: 0.3893694	total: 155ms	remaining: 15.4ms
91:	learn: 0.3893003	total: 157ms	remaining: 13.6ms
92:	learn: 0.3891856	total: 159ms	remaining: 11.9ms
93:	learn: 0.3889837	total: 160ms	remaining: 10.2ms
94:	learn: 0.3889048	total: 162ms	remaining: 8.52ms
95:	learn: 0.3886129	total: 164ms	remaining: 6.81ms
96:	learn: 0.3885017	total: 165ms	remaining: 5.11ms
97:	learn: 0.3882678	total: 167ms	remaining: 3.4ms
98:	learn: 0.3882246	total: 168ms	remaining: 1.7ms
99:	learn: 0.3880680	total: 170ms	remaining: 0us

In [26]:
test_score = best_model.score(X_test, y_test)

In [28]:
cv_results = pd.DataFrame(clf.cv_results_)

In [29]:
best_params = clf.best_params_

In [30]:
best_params

{'min_data_in_leaf': 10,
 'loss_function': 'MultiClass',
 'learning_rate': 0.1,
 'iterations': 100,
 'depth': 3}

In [38]:
model_best = CatBoostClassifier(**best_params, random_seed=random_seed, task_type=task_type)

In [31]:
prediction = best_model.predict(X_test)
probas = best_model.predict_proba(X_test)[:, 1]

In [32]:
metrics = {}

In [33]:
from sklearn.metrics import confusion_matrix, roc_auc_score, precision_score, recall_score, f1_score, log_loss

In [34]:
_, err1, _, err2 = confusion_matrix(y_test, prediction, normalize="all").ravel()
auc = roc_auc_score(y_test, probas)
precision = precision_score(y_test, prediction)
recall = recall_score(y_test, prediction)
f1 = f1_score(y_test, prediction)
logloss = log_loss(y_test, prediction)

In [35]:
metrics["err1"] = err1
metrics["err2"] = err2
metrics["auc"] = auc
metrics["precision"] = precision
metrics["recall"] = recall
metrics["f1"] = f1
metrics["logloss"] = logloss

In [36]:
metrics["mean_fit_time"] = cv_results["mean_fit_time"].mean()# среднее время обучения
metrics["std_fit_time"] =  cv_results["std_fit_time"].mean()# стандартное отклонение времени обучения
metrics["mean_test_score"] = cv_results["mean_test_score"].mean()# средний результат на тесте
metrics["std_test_score"] = cv_results["std_test_score"].mean()# стандартное отклонение результата на тесте
metrics["best_score"] = clf.best_score_

In [37]:
pip_requirements = "./requirements.txt"
signature = mlflow.models.infer_signature(X_test, prediction)
input_example = X_test[:10]

/home/mle-user/mle_projects/mlflow/.venv/lib/python3.10/site-packages/mlflow/models/signature.py:212: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  inputs = _infer_schema(model_input) if model_input is not None else None

In [38]:
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "https://storage.yandexcloud.net"
os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("AWS_ACCESS_KEY_ID")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")

In [39]:
mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

In [40]:
experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

In [41]:
best_params

{'min_data_in_leaf': 10,
 'loss_function': 'MultiClass',
 'learning_rate': 0.1,
 'iterations': 100,
 'depth': 3}

In [44]:
REGISTRY_MODEL_NAME

'Applied_hyperparams'

In [45]:
with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    mlflow.log_metrics(metrics)
    mlflow.log_params(best_params)
    cv_info = mlflow.sklearn.log_model(cv, artifact_path="cv")
    model_info = mlflow.catboost.log_model(cb_model=best_model, artifact_path="models",
                                          registered_model_name=REGISTRY_MODEL_NAME,
                                          signature=signature,
                                           input_example=input_example,
                                           pip_requirements=pip_requirements)

Registered model 'Applied_hyperparams' already exists. Creating a new version of this model...
2026/01/23 02:52:01 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: Applied_hyperparams, version 2
Created version '2' of model 'Applied_hyperparams'.