In [23]:
import numpy as np
import pandas as pd
import psycopg as pg
import mlflow
import os
from catboost import CatBoostClassifier
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import matplotlib.pyplot as plt

In [2]:
TABLE_NAME = "clean_users_churn"

TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000

EXPERIMENT_NAME = "Explore_search_hyperparams"
RUN_NAME = 'model_random_search'
REGISTRY_MODEL_NAME = "Applied_hyperparams"

In [3]:
configs = {"sslmode": "require", "target_session_attrs": "read-write"}
db_credits = {
    "host": os.getenv("DB_DESTINATION_HOST"),
    "port": os.getenv("DB_DESTINATION_PORT"),
    "dbname": os.getenv("DB_DESTINATION_NAME"),
    "user": os.getenv("DB_DESTINATION_USER"),
    "password": os.getenv("DB_DESTINATION_PASSWORD")
}

configs.update(db_credits)

In [4]:
with pg.connect(**configs) as conn:
    with conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {TABLE_NAME}")

        data = cur.fetchall()

        columns = [col.name for col in cur.description]

In [5]:
df = pd.DataFrame(data=data, columns=columns)

In [6]:
features = ["monthly_charges", "total_charges", "senior_citizen"]
target = "target"

In [7]:
df[features]

      monthly_charges  total_charges  senior_citizen
0               19.80         202.25               0
1               20.15          20.15               0
2               59.90        3505.10               0
3               59.60        2970.30               0
4               55.30        1530.60               0
...               ...            ...             ...
7019            69.50        1652.10               0
7020            76.00        1588.75               0
7021            93.60        3366.05               0
7022            95.65         778.10               0
7023           100.55        7113.75               0

[7024 rows x 3 columns]

In [9]:
test_size = 0.2
split_column = features

In [15]:
df.sort_values(by=["begin_date"])

,id,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges,internet_service,...,device_protection,tech_support,streaming_tv,streaming_movies,gender,senior_citizen,partner,dependents,multiple_lines,target
3317,3429,9919-KNPOO,2013-10-01,2019-10-01,Two year,Yes,Bank transfer (automatic),104.15,7689.950000,Fiber optic,...,Yes,No,Yes,Yes,Male,1,Yes,No,Yes,1
4462,4612,2211-RMNHO,2013-10-01,2019-10-01,One year,Yes,Bank transfer (automatic),117.80,8684.800000,Fiber optic,...,Yes,Yes,Yes,Yes,Male,0,Yes,No,Yes,1
4367,4515,6178-KFNHS,2013-10-01,2019-10-01,Two year,No,Credit card (automatic),92.45,6440.250000,DSL,...,Yes,Yes,Yes,Yes,Female,1,Yes,Yes,Yes,1
6850,2009,2065-MMKGR,2013-11-01,2019-10-01,Two year,Yes,Credit card (automatic),108.60,7690.900000,Fiber optic,...,Yes,Yes,Yes,Yes,Male,0,Yes,No,Yes,1
951,989,5002-GCQFH,2013-11-01,2019-10-01,Two year,Yes,Electronic check,108.05,7532.150000,Fiber optic,...,Yes,Yes,Yes,Yes,Male,0,No,No,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,753,8405-IGQFX,2020-02-01,NaT,Two year,No,Mailed check,20.25,2291.023009,Fiber optic,...,No,No,No,No,Male,0,No,Yes,No,0
6442,6677,5850-BDWCY,2020-02-01,NaT,Two year,No,Mailed check,73.35,2291.023009,DSL,...,Yes,Yes,Yes,No,Female,0,Yes,Yes,Yes,0
1040,1094,9845-PEEKO,2020-02-01,NaT,Two year,No,Mailed check,25.75,2291.023009,Fiber optic,...,No,No,No,No,Male,0,Yes,Yes,Yes,0
464,491,3649-JPUGY,2020-02-01,NaT,Two year,Yes,Bank transfer (automatic),52.55,2291.023009,DSL,...,Yes,Yes,Yes,No,Female,0,Yes,Yes,No,0
909,936,5787-KXGIY,2020-02-01,NaT,Two year,No,Mailed check,80.85,2291.023009,DSL,...,Yes,No,Yes,Yes,Female,0,Yes,Yes,No,0

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], test_size=test_size, shuffle=False)

In [17]:
X_train

      monthly_charges  total_charges  senior_citizen
3594            18.25         534.70               0
1485            18.40        1057.85               0
6423            18.55         689.00               0
6674            18.70         383.65               0
1113            18.70        1005.70               0
...               ...            ...             ...
5852            94.25        6849.75               0
983             94.30         424.45               1
486             94.30        1818.30               1
3305            94.30        1948.35               0
868             94.30        2679.70               0

[5619 rows x 3 columns]

In [18]:
print(f"Размер выборки для обучения: {X_train.shape}")
print(f"Размер выборки для теста: {X_test.shape}")

Размер выборки для обучения: (5619, 3)
Размер выборки для теста: (1405, 3)

In [19]:
loss_function = "Logloss"
task_type = 'CPU'
random_seed = 0
iterations = 300
verbose = False

In [ ]:
param_grid = {
    'iterations': [50, 100, 300, 500],
    'learning_rate': [0.01, 0.1, 0.3],
    'loss_function': ["Logloss", "MultiClass"],
    'depth': [4, 6, 8, 10],
    'min_data_in_leaf': [50, 100, 200],
}

In [21]:
model = CatBoostClassifier(random_seed=random_seed, task_type=task_type)

In [24]:
cv = GridSearchCV(estimator=model, param_grid=param_grid, cv=2, scoring="roc_auc", n_jobs=-1)

In [25]:
clf = cv.fit(X_train, y_train)

0:	learn: 0.6882585	total: 58.5ms	remaining: 527ms
1:	learn: 0.6835530	total: 59.2ms	remaining: 237ms
2:	learn: 0.6789331	total: 60.2ms	remaining: 140ms
3:	learn: 0.6743958	total: 60.9ms	remaining: 91.4ms
4:	learn: 0.6698802	total: 61.6ms	remaining: 61.6ms
5:	learn: 0.6654726	total: 62.3ms	remaining: 41.5ms
6:	learn: 0.6612372	total: 63.1ms	remaining: 27ms
7:	learn: 0.6571645	total: 63.7ms	remaining: 15.9ms
8:	learn: 0.6530374	total: 64.4ms	remaining: 7.15ms
9:	learn: 0.6489363	total: 65.1ms	remaining: 0us
0:	learn: 0.6876044	total: 49.3ms	remaining: 443ms
1:	learn: 0.6819988	total: 49.9ms	remaining: 200ms
2:	learn: 0.6768104	total: 50.5ms	remaining: 118ms
3:	learn: 0.6715827	total: 51ms	remaining: 76.6ms
4:	learn: 0.6663667	total: 51.6ms	remaining: 51.6ms
5:	learn: 0.6613484	total: 52.2ms	remaining: 34.8ms
6:	learn: 0.6562736	total: 52.8ms	remaining: 22.6ms
7:	learn: 0.6514023	total: 53.3ms	remaining: 13.3ms
8:	learn: 0.6465034	total: 53.9ms	remaining: 5.99ms
9:	learn: 0.6419050	total: 54.5ms	remaining: 0us
0:	learn: 0.6876044	total: 3.28ms	remaining: 29.5ms
1:	learn: 0.6819988	total: 5.18ms	remaining: 20.7ms
0:	learn: 0.6882585	total: 4.24ms	remaining: 38.1ms
2:	learn: 0.6768104	total: 6.85ms	remaining: 16ms
3:	learn: 0.6715827	total: 8.24ms	remaining: 12.4ms
1:	learn: 0.6835530	total: 5.88ms	remaining: 23.5ms
4:	learn: 0.6663667	total: 9.72ms	remaining: 9.72ms
2:	learn: 0.6789331	total: 7.61ms	remaining: 17.8ms
5:	learn: 0.6613484	total: 11.4ms	remaining: 7.59ms
6:	learn: 0.6562736	total: 12.9ms	remaining: 5.53ms
3:	learn: 0.6743958	total: 10.3ms	remaining: 15.5ms
7:	learn: 0.6514023	total: 14.6ms	remaining: 3.65ms
8:	learn: 0.6465034	total: 15.6ms	remaining: 1.73ms
4:	learn: 0.6698802	total: 12.6ms	remaining: 12.6ms
9:	learn: 0.6419050	total: 17.4ms	remaining: 0us
5:	learn: 0.6654726	total: 13.5ms	remaining: 9.03ms
6:	learn: 0.6612372	total: 14.1ms	remaining: 6.06ms
7:	learn: 0.6571645	total: 14.7ms	remaining: 3.68ms
8:	learn: 0.6530374	total: 15.3ms	remaining: 1.7ms
9:	learn: 0.6489363	total: 15.9ms	remaining: 0us
0:	learn: 0.6882585	total: 743us	remaining: 6.69ms
1:	learn: 0.6835530	total: 1.39ms	remaining: 5.54ms
2:	learn: 0.6789331	total: 1.98ms	remaining: 4.62ms
3:	learn: 0.6743958	total: 2.58ms	remaining: 3.86ms
4:	learn: 0.6698802	total: 3.16ms	remaining: 3.16ms
5:	learn: 0.6654726	total: 3.73ms	remaining: 2.48ms
6:	learn: 0.6612372	total: 4.31ms	remaining: 1.85ms
7:	learn: 0.6571645	total: 4.88ms	remaining: 1.22ms
8:	learn: 0.6530374	total: 5.46ms	remaining: 606us
9:	learn: 0.6489363	total: 6.05ms	remaining: 0us
0:	learn: 0.6876044	total: 598us	remaining: 5.38ms
1:	learn: 0.6819988	total: 1.12ms	remaining: 4.48ms
2:	learn: 0.6768104	total: 1.61ms	remaining: 3.76ms
3:	learn: 0.6715827	total: 2.09ms	remaining: 3.14ms
4:	learn: 0.6663667	total: 2.57ms	remaining: 2.57ms
5:	learn: 0.6613484	total: 3.23ms	remaining: 2.15ms
6:	learn: 0.6562736	total: 3.69ms	remaining: 1.58ms
7:	learn: 0.6514023	total: 4.36ms	remaining: 1.09ms
8:	learn: 0.6465034	total: 5.06ms	remaining: 562us
9:	learn: 0.6419050	total: 5.71ms	remaining: 0us
0:	learn: 0.6881513	total: 1.38ms	remaining: 12.4ms
1:	learn: 0.6833085	total: 2.55ms	remaining: 10.2ms
2:	learn: 0.6785046	total: 3.84ms	remaining: 8.97ms
3:	learn: 0.6738448	total: 5.98ms	remaining: 8.98ms
0:	learn: 0.6875005	total: 3.4ms	remaining: 30.6ms
4:	learn: 0.6694774	total: 8.77ms	remaining: 8.77ms
1:	learn: 0.6820238	total: 6.29ms	remaining: 25.2ms
5:	learn: 0.6649898	total: 11.3ms	remaining: 7.55ms
6:	learn: 0.6606498	total: 14.7ms	remaining: 6.32ms
2:	learn: 0.6769052	total: 8.91ms	remaining: 20.8ms
7:	learn: 0.6563640	total: 16.3ms	remaining: 4.07ms
3:	learn: 0.6715897	total: 12.1ms	remaining: 18.2ms
8:	learn: 0.6520223	total: 22.6ms	remaining: 2.51ms
4:	learn: 0.6662544	total: 14.7ms	remaining: 14.7ms
9:	learn: 0.6479282	total: 24ms	remaining: 0us
5:	learn: 0.6609131	total: 16.8ms	remaining: 11.2ms
6:	learn: 0.6559658	total: 19.3ms	remaining: 8.29ms
7:	learn: 0.6514303	total: 20.8ms	remaining: 5.21ms
8:	learn: 0.6466956	total: 22.1ms	remaining: 2.45ms
9:	learn: 0.6417852	total: 23.3ms	remaining: 0us
0:	learn: 0.6881513	total: 1.44ms	remaining: 13ms
1:	learn: 0.6833085	total: 2.71ms	remaining: 10.8ms
2:	learn: 0.6785046	total: 3.99ms	remaining: 9.32ms
3:	learn: 0.6738448	total: 5.25ms	remaining: 7.87ms
4:	learn: 0.6694774	total: 6.46ms	remaining: 6.46ms
5:	learn: 0.6649898	total: 7.7ms	remaining: 5.13ms
6:	learn: 0.6606498	total: 8.91ms	remaining: 3.82ms
7:	learn: 0.6563640	total: 10.5ms	remaining: 2.62ms
8:	learn: 0.6520223	total: 12ms	remaining: 1.33ms
9:	learn: 0.6479282	total: 13.5ms	remaining: 0us
0:	learn: 0.6875005	total: 3.43ms	remaining: 30.9ms
1:	learn: 0.6820238	total: 4.64ms	remaining: 18.6ms
2:	learn: 0.6769052	total: 6.02ms	remaining: 14ms
3:	learn: 0.6715897	total: 7.64ms	remaining: 11.5ms
4:	learn: 0.6662544	total: 8.79ms	remaining: 8.79ms
5:	learn: 0.6609131	total: 9.93ms	remaining: 6.62ms
6:	learn: 0.6559658	total: 11.1ms	remaining: 4.75ms
7:	learn: 0.6514303	total: 12.3ms	remaining: 3.07ms
8:	learn: 0.6466956	total: 13.5ms	remaining: 1.5ms
9:	learn: 0.6417852	total: 14.7ms	remaining: 0us
0:	learn: 0.6875005	total: 1.26ms	remaining: 11.4ms
1:	learn: 0.6820238	total: 2.83ms	remaining: 11.3ms
2:	learn: 0.6769052	total: 4.08ms	remaining: 9.52ms
3:	learn: 0.6715897	total: 5.32ms	remaining: 7.98ms
4:	learn: 0.6662544	total: 6.49ms	remaining: 6.49ms
5:	learn: 0.6609131	total: 7.67ms	remaining: 5.11ms
6:	learn: 0.6559658	total: 8.85ms	remaining: 3.79ms
7:	learn: 0.6514303	total: 10ms	remaining: 2.51ms
8:	learn: 0.6466956	total: 11.3ms	remaining: 1.25ms
9:	learn: 0.6417852	total: 12.4ms	remaining: 0us
0:	learn: 0.6881513	total: 1.39ms	remaining: 12.5ms
1:	learn: 0.6833085	total: 2.59ms	remaining: 10.3ms
2:	learn: 0.6785046	total: 3.85ms	remaining: 9ms
3:	learn: 0.6738448	total: 4.99ms	remaining: 7.48ms
4:	learn: 0.6694774	total: 6.09ms	remaining: 6.09ms
5:	learn: 0.6649898	total: 7.22ms	remaining: 4.82ms
6:	learn: 0.6606498	total: 8.47ms	remaining: 3.63ms
7:	learn: 0.6563640	total: 9.71ms	remaining: 2.43ms
8:	learn: 0.6520223	total: 11ms	remaining: 1.22ms
9:	learn: 0.6479282	total: 12.2ms	remaining: 0us
0:	learn: 0.6464073	total: 750us	remaining: 6.76ms
1:	learn: 0.6086259	total: 1.62ms	remaining: 6.49ms
2:	learn: 0.5755443	total: 2.18ms	remaining: 5.08ms
3:	learn: 0.5496501	total: 2.73ms	remaining: 4.1ms
4:	learn: 0.5261348	total: 3.31ms	remaining: 3.31ms
5:	learn: 0.5065706	total: 3.87ms	remaining: 2.58ms
6:	learn: 0.4884386	total: 4.44ms	remaining: 1.9ms
7:	learn: 0.4734537	total: 5.05ms	remaining: 1.26ms
0:	learn: 0.6401926	total: 681us	remaining: 6.13ms
1:	learn: 0.5949026	total: 1.28ms	remaining: 5.11ms
2:	learn: 0.5592501	total: 1.93ms	remaining: 4.49ms
3:	learn: 0.5277705	total: 2.6ms	remaining: 3.9ms
4:	learn: 0.5005452	total: 3.24ms	remaining: 3.24ms
5:	learn: 0.4777804	total: 3.85ms	remaining: 2.56ms
6:	learn: 0.4577290	total: 4.35ms	remaining: 1.86ms
7:	learn: 0.4405271	total: 4.91ms	remaining: 1.23ms
8:	learn: 0.4251705	total: 5.42ms	remaining: 602us
9:	learn: 0.4123807	total: 5.93ms	remaining: 0us
8:	learn: 0.4601212	total: 8.77ms	remaining: 974us
9:	learn: 0.4476518	total: 9.82ms	remaining: 0us
0:	learn: 0.6464073	total: 6.24ms	remaining: 56.1ms
1:	learn: 0.6086259	total: 7.6ms	remaining: 30.4ms
2:	learn: 0.5755443	total: 8.28ms	remaining: 19.3ms
3:	learn: 0.5496501	total: 8.96ms	remaining: 13.4ms
4:	learn: 0.5261348	total: 9.56ms	remaining: 9.56ms
5:	learn: 0.5065706	total: 10.1ms	remaining: 6.74ms
6:	learn: 0.4884386	total: 10.7ms	remaining: 4.59ms
7:	learn: 0.4734537	total: 11.3ms	remaining: 2.82ms
8:	learn: 0.4601212	total: 11.9ms	remaining: 1.32ms
0:	learn: 0.6401926	total: 9.29ms	remaining: 83.7ms
9:	learn: 0.4476518	total: 12.4ms	remaining: 0us
1:	learn: 0.5949026	total: 10.1ms	remaining: 40.5ms
2:	learn: 0.5592501	total: 10.8ms	remaining: 25.2ms
3:	learn: 0.5277705	total: 11.4ms	remaining: 17ms
4:	learn: 0.5005452	total: 11.9ms	remaining: 11.9ms
5:	learn: 0.4777804	total: 12.6ms	remaining: 8.37ms
6:	learn: 0.4577290	total: 13.1ms	remaining: 5.63ms
7:	learn: 0.4405271	total: 13.7ms	remaining: 3.44ms
8:	learn: 0.4251705	total: 14.3ms	remaining: 1.59ms
9:	learn: 0.4123807	total: 14.9ms	remaining: 0us
0:	learn: 0.6401926	total: 663us	remaining: 5.97ms
1:	learn: 0.5949026	total: 1.59ms	remaining: 6.35ms
0:	learn: 0.6464073	total: 590us	remaining: 5.32ms
2:	learn: 0.5592501	total: 3.89ms	remaining: 9.08ms
1:	learn: 0.6086259	total: 1.97ms	remaining: 7.87ms
2:	learn: 0.5755443	total: 2.49ms	remaining: 5.81ms
3:	learn: 0.5496501	total: 3.21ms	remaining: 4.81ms
4:	learn: 0.5261348	total: 3.92ms	remaining: 3.92ms
5:	learn: 0.5065706	total: 4.63ms	remaining: 3.09ms
3:	learn: 0.5277705	total: 7.64ms	remaining: 11.5ms
6:	learn: 0.4884386	total: 5.17ms	remaining: 2.21ms
7:	learn: 0.4734537	total: 5.69ms	remaining: 1.42ms
4:	learn: 0.5005452	total: 9.46ms	remaining: 9.46ms
5:	learn: 0.4777804	total: 10.2ms	remaining: 6.79ms
6:	learn: 0.4577290	total: 11.3ms	remaining: 4.82ms
8:	learn: 0.4601212	total: 7.05ms	remaining: 782us
9:	learn: 0.4476518	total: 7.76ms	remaining: 0us
7:	learn: 0.4405271	total: 12.8ms	remaining: 3.19ms
8:	learn: 0.4251705	total: 13.9ms	remaining: 1.54ms
9:	learn: 0.4123807	total: 14.6ms	remaining: 0us
0:	learn: 0.6453877	total: 1.35ms	remaining: 12.1ms
1:	learn: 0.6062939	total: 4.87ms	remaining: 19.5ms
0:	learn: 0.6391729	total: 4.22ms	remaining: 38ms
2:	learn: 0.5729923	total: 7.82ms	remaining: 18.2ms
1:	learn: 0.5950822	total: 7.42ms	remaining: 29.7ms
3:	learn: 0.5451078	total: 11ms	remaining: 16.5ms
2:	learn: 0.5600737	total: 10.6ms	remaining: 24.7ms
4:	learn: 0.5219056	total: 14.3ms	remaining: 14.3ms
3:	learn: 0.5283031	total: 12.9ms	remaining: 19.4ms
5:	learn: 0.5008036	total: 17ms	remaining: 11.3ms
4:	learn: 0.5008032	total: 15.7ms	remaining: 15.7ms
5:	learn: 0.4763271	total: 17.8ms	remaining: 11.8ms
6:	learn: 0.4841589	total: 20.2ms	remaining: 8.64ms
6:	learn: 0.4567803	total: 20.7ms	remaining: 8.89ms
7:	learn: 0.4688770	total: 23.7ms	remaining: 5.94ms
7:	learn: 0.4412035	total: 23.4ms	remaining: 5.84ms
8:	learn: 0.4557230	total: 26.5ms	remaining: 2.94ms
8:	learn: 0.4266299	total: 26.3ms	remaining: 2.92ms
9:	learn: 0.4440183	total: 29.1ms	remaining: 0us
9:	learn: 0.4128481	total: 28.9ms	remaining: 0us
0:	learn: 0.6391729	total: 4.74ms	remaining: 42.7ms
1:	learn: 0.5950822	total: 6.3ms	remaining: 25.2ms
0:	learn: 0.6453877	total: 5.08ms	remaining: 45.7ms
2:	learn: 0.5600737	total: 7.84ms	remaining: 18.3ms
3:	learn: 0.5283031	total: 9.98ms	remaining: 15ms
1:	learn: 0.6062939	total: 9.89ms	remaining: 39.6ms
2:	learn: 0.5729923	total: 11.8ms	remaining: 27.5ms
4:	learn: 0.5008032	total: 15.7ms	remaining: 15.7ms
5:	learn: 0.4763271	total: 17.2ms	remaining: 11.5ms
6:	learn: 0.4567803	total: 18.8ms	remaining: 8.07ms
3:	learn: 0.5451078	total: 16ms	remaining: 23.9ms
7:	learn: 0.4412035	total: 20.4ms	remaining: 5.1ms
4:	learn: 0.5219056	total: 19.3ms	remaining: 19.3ms
5:	learn: 0.5008036	total: 22ms	remaining: 14.7ms
8:	learn: 0.4266299	total: 26.7ms	remaining: 2.97ms
9:	learn: 0.4128481	total: 27.8ms	remaining: 0us
6:	learn: 0.4841589	total: 25ms	remaining: 10.7ms
7:	learn: 0.4688770	total: 26.2ms	remaining: 6.56ms
8:	learn: 0.4557230	total: 28.4ms	remaining: 3.15ms
9:	learn: 0.4440183	total: 29.9ms	remaining: 0us
0:	learn: 0.6453877	total: 2.88ms	remaining: 25.9ms
1:	learn: 0.6062939	total: 4.44ms	remaining: 17.8ms
2:	learn: 0.5729923	total: 6.25ms	remaining: 14.6ms
3:	learn: 0.5451078	total: 7.57ms	remaining: 11.3ms
4:	learn: 0.5219056	total: 8.83ms	remaining: 8.83ms
0:	learn: 0.6391729	total: 1.26ms	remaining: 11.4ms
1:	learn: 0.5950822	total: 2.42ms	remaining: 9.66ms
2:	learn: 0.5600737	total: 3.73ms	remaining: 8.72ms
3:	learn: 0.5283031	total: 4.83ms	remaining: 7.24ms
4:	learn: 0.5008032	total: 6.05ms	remaining: 6.05ms
5:	learn: 0.4763271	total: 7.4ms	remaining: 4.93ms
6:	learn: 0.4567803	total: 8.48ms	remaining: 3.63ms
5:	learn: 0.5008036	total: 20.3ms	remaining: 13.5ms
7:	learn: 0.4412035	total: 11.2ms	remaining: 2.8ms
8:	learn: 0.4266299	total: 12.4ms	remaining: 1.37ms
9:	learn: 0.4128481	total: 13.9ms	remaining: 0us
6:	learn: 0.4841589	total: 23ms	remaining: 9.84ms
7:	learn: 0.4688770	total: 25.3ms	remaining: 6.33ms
8:	learn: 0.4557230	total: 26.5ms	remaining: 2.94ms
9:	learn: 0.4440183	total: 29.5ms	remaining: 0us
0:	learn: 0.5668853	total: 774us	remaining: 6.97ms
1:	learn: 0.4940492	total: 3.86ms	remaining: 15.5ms
0:	learn: 0.5502088	total: 3.09ms	remaining: 27.8ms
2:	learn: 0.4468537	total: 6.47ms	remaining: 15.1ms
1:	learn: 0.4667158	total: 5.54ms	remaining: 22.2ms
2:	learn: 0.4166009	total: 6.68ms	remaining: 15.6ms
3:	learn: 0.4185529	total: 8.26ms	remaining: 12.4ms
3:	learn: 0.3852502	total: 8.42ms	remaining: 12.6ms
4:	learn: 0.4008433	total: 10.1ms	remaining: 10.1ms
4:	learn: 0.3619933	total: 10.2ms	remaining: 10.2ms
5:	learn: 0.3473426	total: 11.9ms	remaining: 7.93ms
5:	learn: 0.3845063	total: 13.3ms	remaining: 8.87ms
6:	learn: 0.3367169	total: 14.1ms	remaining: 6.03ms
7:	learn: 0.3271284	total: 15.7ms	remaining: 3.91ms
6:	learn: 0.3725928	total: 15.2ms	remaining: 6.5ms
8:	learn: 0.3224908	total: 17.1ms	remaining: 1.9ms
9:	learn: 0.3172528	total: 18.2ms	remaining: 0us
7:	learn: 0.3649329	total: 16.8ms	remaining: 4.19ms
8:	learn: 0.3604455	total: 17.6ms	remaining: 1.95ms
9:	learn: 0.3566339	total: 18.2ms	remaining: 0us
0:	learn: 0.5668853	total: 734us	remaining: 6.61ms
1:	learn: 0.4940492	total: 1.39ms	remaining: 5.58ms
2:	learn: 0.4468537	total: 2.08ms	remaining: 4.85ms
0:	learn: 0.5502088	total: 683us	remaining: 6.15ms
1:	learn: 0.4667158	total: 1.36ms	remaining: 5.46ms
2:	learn: 0.4166009	total: 1.97ms	remaining: 4.59ms
3:	learn: 0.3852502	total: 2.55ms	remaining: 3.83ms
4:	learn: 0.3619933	total: 3.14ms	remaining: 3.14ms
5:	learn: 0.3473426	total: 3.77ms	remaining: 2.51ms
6:	learn: 0.3367169	total: 4.42ms	remaining: 1.9ms
7:	learn: 0.3271284	total: 5.13ms	remaining: 1.28ms
8:	learn: 0.3224908	total: 5.66ms	remaining: 628us
9:	learn: 0.3172528	total: 6.15ms	remaining: 0us
3:	learn: 0.4185529	total: 12.2ms	remaining: 18.3ms
4:	learn: 0.4008433	total: 13.1ms	remaining: 13.1ms
5:	learn: 0.3845063	total: 13.8ms	remaining: 9.18ms
6:	learn: 0.3725928	total: 14.4ms	remaining: 6.17ms
7:	learn: 0.3649329	total: 15ms	remaining: 3.75ms
8:	learn: 0.3604455	total: 15.6ms	remaining: 1.74ms
9:	learn: 0.3566339	total: 16.2ms	remaining: 0us
0:	learn: 0.5668853	total: 671us	remaining: 6.05ms
1:	learn: 0.4940492	total: 1.57ms	remaining: 6.29ms
2:	learn: 0.4468537	total: 2.21ms	remaining: 5.17ms
3:	learn: 0.4185529	total: 2.86ms	remaining: 4.29ms
4:	learn: 0.4008433	total: 3.49ms	remaining: 3.49ms
5:	learn: 0.3845063	total: 4.11ms	remaining: 2.74ms
6:	learn: 0.3725928	total: 4.76ms	remaining: 2.04ms
7:	learn: 0.3649329	total: 5.36ms	remaining: 1.34ms
8:	learn: 0.3604455	total: 5.96ms	remaining: 662us
9:	learn: 0.3566339	total: 6.58ms	remaining: 0us
0:	learn: 0.5502088	total: 601us	remaining: 5.41ms
1:	learn: 0.4667158	total: 1.31ms	remaining: 5.24ms
2:	learn: 0.4166009	total: 1.99ms	remaining: 4.65ms
3:	learn: 0.3852502	total: 2.52ms	remaining: 3.78ms
4:	learn: 0.3619933	total: 3.21ms	remaining: 3.21ms
5:	learn: 0.3473426	total: 3.7ms	remaining: 2.47ms
6:	learn: 0.3367169	total: 4.31ms	remaining: 1.84ms
7:	learn: 0.3271284	total: 5.06ms	remaining: 1.26ms
8:	learn: 0.3224908	total: 5.63ms	remaining: 625us
9:	learn: 0.3172528	total: 6.34ms	remaining: 0us
0:	learn: 0.5643261	total: 1.33ms	remaining: 11.9ms
1:	learn: 0.4924523	total: 2.44ms	remaining: 9.78ms
2:	learn: 0.4464566	total: 5.26ms	remaining: 12.3ms
3:	learn: 0.4157330	total: 7.79ms	remaining: 11.7ms
0:	learn: 0.5476031	total: 5ms	remaining: 45ms
1:	learn: 0.4669278	total: 7.03ms	remaining: 28.1ms
4:	learn: 0.3961612	total: 10.8ms	remaining: 10.8ms
2:	learn: 0.4199004	total: 9.68ms	remaining: 22.6ms
5:	learn: 0.3910618	total: 13.5ms	remaining: 9ms
3:	learn: 0.3870800	total: 12.4ms	remaining: 18.6ms
6:	learn: 0.3802272	total: 16.1ms	remaining: 6.91ms
4:	learn: 0.3638688	total: 14.6ms	remaining: 14.6ms
7:	learn: 0.3716409	total: 19ms	remaining: 4.74ms
5:	learn: 0.3481627	total: 17.6ms	remaining: 11.7ms
6:	learn: 0.3384390	total: 19.5ms	remaining: 8.35ms
8:	learn: 0.3641537	total: 21.8ms	remaining: 2.42ms
7:	learn: 0.3307379	total: 22.2ms	remaining: 5.56ms
9:	learn: 0.3599636	total: 25.1ms	remaining: 0us
8:	learn: 0.3252706	total: 24.3ms	remaining: 2.7ms
9:	learn: 0.3209522	total: 25.5ms	remaining: 0us
0:	learn: 0.5643261	total: 1.39ms	remaining: 12.5ms
1:	learn: 0.4924523	total: 2.54ms	remaining: 10.2ms
0:	learn: 0.5476031	total: 1.27ms	remaining: 11.5ms
2:	learn: 0.4464566	total: 6.59ms	remaining: 15.4ms
1:	learn: 0.4669278	total: 3.09ms	remaining: 12.4ms
3:	learn: 0.4157330	total: 7.72ms	remaining: 11.6ms
2:	learn: 0.4199004	total: 6.05ms	remaining: 14.1ms
4:	learn: 0.3961612	total: 10.3ms	remaining: 10.3ms
5:	learn: 0.3910618	total: 11.3ms	remaining: 7.53ms
3:	learn: 0.3870800	total: 9.4ms	remaining: 14.1ms
6:	learn: 0.3802272	total: 12.5ms	remaining: 5.37ms
4:	learn: 0.3638688	total: 10.6ms	remaining: 10.6ms
5:	learn: 0.3481627	total: 11.8ms	remaining: 7.9ms
7:	learn: 0.3716409	total: 13.6ms	remaining: 3.41ms
6:	learn: 0.3384390	total: 14.8ms	remaining: 6.33ms
8:	learn: 0.3641537	total: 16.2ms	remaining: 1.8ms
7:	learn: 0.3307379	total: 17.4ms	remaining: 4.34ms
8:	learn: 0.3252706	total: 18.8ms	remaining: 2.09ms
9:	learn: 0.3209522	total: 20.1ms	remaining: 0us
9:	learn: 0.3599636	total: 21.2ms	remaining: 0us
0:	learn: 0.5643261	total: 1.63ms	remaining: 14.7ms
1:	learn: 0.4924523	total: 4.28ms	remaining: 17.1ms
2:	learn: 0.4464566	total: 5.75ms	remaining: 13.4ms
3:	learn: 0.4157330	total: 7.18ms	remaining: 10.8ms
4:	learn: 0.3961612	total: 8.53ms	remaining: 8.53ms
5:	learn: 0.3910618	total: 9.69ms	remaining: 6.46ms
6:	learn: 0.3802272	total: 11.2ms	remaining: 4.82ms
7:	learn: 0.3716409	total: 12.8ms	remaining: 3.21ms
0:	learn: 0.5476031	total: 1.19ms	remaining: 10.7ms
1:	learn: 0.4669278	total: 3.73ms	remaining: 14.9ms
2:	learn: 0.4199004	total: 5.04ms	remaining: 11.8ms
8:	learn: 0.3641537	total: 14.1ms	remaining: 1.57ms
3:	learn: 0.3870800	total: 7.57ms	remaining: 11.4ms
9:	learn: 0.3599636	total: 15.6ms	remaining: 0us
4:	learn: 0.3638688	total: 8.88ms	remaining: 8.88ms
5:	learn: 0.3481627	total: 10.3ms	remaining: 6.83ms
6:	learn: 0.3384390	total: 11.5ms	remaining: 4.93ms
7:	learn: 0.3307379	total: 12.9ms	remaining: 3.22ms
8:	learn: 0.3252706	total: 14.2ms	remaining: 1.57ms
9:	learn: 0.3209522	total: 15.4ms	remaining: 0us
0:	learn: 0.6882585	total: 717us	remaining: 20.8ms
1:	learn: 0.6835530	total: 1.52ms	remaining: 21.3ms
0:	learn: 0.6876044	total: 529us	remaining: 15.4ms
1:	learn: 0.6819988	total: 1.04ms	remaining: 14.6ms
2:	learn: 0.6768104	total: 1.54ms	remaining: 13.8ms
2:	learn: 0.6789331	total: 6.67ms	remaining: 60ms
3:	learn: 0.6715827	total: 2.07ms	remaining: 13.4ms
4:	learn: 0.6663667	total: 2.58ms	remaining: 12.9ms
3:	learn: 0.6743958	total: 9.43ms	remaining: 61.3ms
5:	learn: 0.6613484	total: 3.1ms	remaining: 12.4ms
6:	learn: 0.6562736	total: 3.6ms	remaining: 11.8ms
4:	learn: 0.6698802	total: 12.1ms	remaining: 60.5ms
5:	learn: 0.6654726	total: 13.5ms	remaining: 54.2ms
6:	learn: 0.6612372	total: 14.2ms	remaining: 46.7ms
7:	learn: 0.6571645	total: 14.9ms	remaining: 40.9ms
8:	learn: 0.6530374	total: 15.6ms	remaining: 36.4ms
9:	learn: 0.6489363	total: 16.4ms	remaining: 32.7ms
10:	learn: 0.6449005	total: 17.1ms	remaining: 29.5ms
11:	learn: 0.6409149	total: 17.8ms	remaining: 26.7ms
7:	learn: 0.6514023	total: 4.17ms	remaining: 11.5ms
8:	learn: 0.6465034	total: 4.78ms	remaining: 11.1ms
9:	learn: 0.6419050	total: 5.39ms	remaining: 10.8ms
10:	learn: 0.6371519	total: 6.02ms	remaining: 10.4ms
11:	learn: 0.6324925	total: 6.63ms	remaining: 9.95ms
12:	learn: 0.6369290	total: 23.8ms	remaining: 31.1ms
12:	learn: 0.6282043	total: 9.89ms	remaining: 12.9ms
13:	learn: 0.6236975	total: 10.5ms	remaining: 12.1ms
14:	learn: 0.6191809	total: 11ms	remaining: 11ms

In [26]:
print("Лучшие гиперпараметры:", clf.best_params_)
print("Лучший счет:", clf.best_score_)

Лучшие гиперпараметры: {'depth': 4, 'iterations': 30, 'learning_rate': 0.3, 'loss_function': 'MultiClass', 'min_data_in_leaf': 50}
Лучший счет: 0.7746747004484371

In [27]:
best_model = clf.best_estimator_

In [29]:
best_model.fit(X_train, y_train)

0:	learn: 0.5884494	total: 2.28ms	remaining: 66.2ms
1:	learn: 0.5270160	total: 4.14ms	remaining: 57.9ms
2:	learn: 0.4924421	total: 6.07ms	remaining: 54.6ms
3:	learn: 0.4669546	total: 8.04ms	remaining: 52.2ms
4:	learn: 0.4517155	total: 9.96ms	remaining: 49.8ms
5:	learn: 0.4395070	total: 11.8ms	remaining: 47.1ms
6:	learn: 0.4320826	total: 13.6ms	remaining: 44.8ms
7:	learn: 0.4269096	total: 16.2ms	remaining: 44.7ms
8:	learn: 0.4239272	total: 19.7ms	remaining: 46ms
9:	learn: 0.4219345	total: 22.4ms	remaining: 44.7ms
10:	learn: 0.4192349	total: 24.6ms	remaining: 42.6ms
11:	learn: 0.4171019	total: 27ms	remaining: 40.5ms
12:	learn: 0.4156591	total: 28.9ms	remaining: 37.8ms
13:	learn: 0.4144717	total: 30.7ms	remaining: 35.1ms
14:	learn: 0.4133922	total: 32.5ms	remaining: 32.5ms
15:	learn: 0.4126900	total: 34.2ms	remaining: 30ms
16:	learn: 0.4126764	total: 35.7ms	remaining: 27.3ms
17:	learn: 0.4120494	total: 37.4ms	remaining: 25ms
18:	learn: 0.4116030	total: 39.2ms	remaining: 22.7ms
19:	learn: 0.4110442	total: 41ms	remaining: 20.5ms
20:	learn: 0.4103686	total: 42.7ms	remaining: 18.3ms
21:	learn: 0.4098914	total: 44.4ms	remaining: 16.2ms
22:	learn: 0.4094962	total: 46.2ms	remaining: 14.1ms
23:	learn: 0.4088733	total: 48.1ms	remaining: 12ms
24:	learn: 0.4082794	total: 50ms	remaining: 9.99ms
25:	learn: 0.4078149	total: 51.9ms	remaining: 7.98ms
26:	learn: 0.4075005	total: 53.8ms	remaining: 5.97ms
27:	learn: 0.4072313	total: 55.5ms	remaining: 3.97ms
28:	learn: 0.4066355	total: 57.3ms	remaining: 1.97ms
29:	learn: 0.4061633	total: 59.1ms	remaining: 0us

In [30]:
test_score = best_model.score(X_test, y_test)

In [34]:
cv_results = pd.DataFrame(clf.cv_results_)

In [36]:
best_params = clf.best_params_

In [37]:
best_params

{'depth': 4,
 'iterations': 30,
 'learning_rate': 0.3,
 'loss_function': 'MultiClass',
 'min_data_in_leaf': 50}

In [38]:
model_best = CatBoostClassifier(**best_params, random_seed=random_seed, task_type=task_type)

In [53]:
prediction = best_model.predict(X_test)
probas = best_model.predict_proba(X_test)[:, 1]

In [42]:
metrics = {}

In [43]:
from sklearn.metrics import confusion_matrix, roc_auc_score, precision_score, recall_score, f1_score, log_loss

In [54]:
_, err1, _, err2 = confusion_matrix(y_test, prediction, normalize="all").ravel()
auc = roc_auc_score(y_test, probas)
precision = precision_score(y_test, prediction)
recall = recall_score(y_test, prediction)
f1 = f1_score(y_test, prediction)
logloss = log_loss(y_test, prediction)

In [55]:
metrics["err1"] = err1
metrics["err2"] = err2
metrics["auc"] = auc
metrics["precision"] = precision
metrics["recall"] = recall
metrics["f1"] = f1
metrics["logloss"] = logloss

In [57]:
metrics["mean_fit_time"] = cv_results["mean_fit_time"].mean()# среднее время обучения
metrics["std_fit_time"] =  cv_results["std_fit_time"].mean()# стандартное отклонение времени обучения
metrics["mean_test_score"] = cv_results["mean_test_score"].mean()# средний результат на тесте
metrics["std_test_score"] = cv_results["std_test_score"].mean()# стандартное отклонение результата на тесте
metrics["best_score"] = clf.best_score_

In [78]:
pip_requirements = "./requirements.txt"
signature = mlflow.models.infer_signature(X_test, prediction)
input_example = X_test[:10]

/home/mle-user/mle_projects/mlflow/.venv/lib/python3.10/site-packages/mlflow/models/signature.py:212: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  inputs = _infer_schema(model_input) if model_input is not None else None

In [65]:
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "https://storage.yandexcloud.net"
os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("AWS_ACCESS_KEY_ID")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")

In [66]:
mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

In [71]:
experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

In [73]:
best_params

{'depth': 4,
 'iterations': 30,
 'learning_rate': 0.3,
 'loss_function': 'MultiClass',
 'min_data_in_leaf': 50}

In [79]:
with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    mlflow.log_metrics(metrics)
    mlflow.log_params(best_params)
    cv_info = mlflow.sklearn.log_model(cv, artifact_path="cv")
    model_info = mlflow.catboost.log_model(cb_model=best_model, artifact_path="models",
                                          registered_model_name=REGISTRY_MODEL_NAME,
                                          signature=signature,
                                           input_example=input_example,
                                           pip_requirements=pip_requirements)

Successfully registered model 'Applied_hyperparams'.
2026/01/22 15:28:11 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: Applied_hyperparams, version 1
Created version '1' of model 'Applied_hyperparams'.